<?php

$WEEK_DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

$stores = $block->getStores();

//Get the first store
if (empty($_REQUEST["storeId"])) {
    foreach ($stores as $store) {
        $_REQUEST["storeId"] = $store->getId();
        break;
    }
}

//set the data target
if (empty($_REQUEST["data-target"])) {
    $_REQUEST["data-target"] = "warehouse";
}

if (!empty($_REQUEST["deleteId"])) {
    $block->deleteShift($_REQUEST["deleteId"]);
}

if (!empty($_REQUEST["weekDay"]) && !empty($_REQUEST["description"]) && !empty($_REQUEST["timeFrom"])&& !empty($_REQUEST["timeTo"]) && !empty($_REQUEST["price"])) {
    $block->addShift($_REQUEST["storeId"], $_REQUEST["weekDay"], $_REQUEST["description"], $_REQUEST["timeFrom"], $_REQUEST["timeTo"], $_REQUEST["price"], $_REQUEST["cutoffTime"]);
}


$shifts = $block->getShifts($_REQUEST["storeId"]);
?>
<link href="http://picup.co.za/assets/css/style.css" rel="stylesheet" />
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <button type="button" class="picupMenu btn btn-primary" data-target="warehouse">My Warehouse</button>
            <button type="button" class="picupMenu btn btn-primary" data-target="buckets">Buckets</button>
            <a href="<?=$block->getUrl("adminhtml/system_config/edit/section/carriers");?>" class="picupMenu btn btn-primary" data-target="shipping-settings">Store Settings</a>
        </div>
    </div>
    <hr/>
    <div id="warehouse" class="picupContent row">
        <div class="col-md-12">
            <iframe frameborder="0" style="width:100%; height: 90vh" src="https://staging.picup.co.za/login"></iframe>
        </div>
    </div>
    <form class="form" name="formShifts" data-mage-init='{
                "validation":{
                        "rules": {
                                "description": {
                                        "required":true
                                }
                        }
                }
        }'>
        <div id="buckets" class="picupContent">
            <div class="row">
                <div class="col-md-12">
                    <input type="hidden" name="data-target" value="buckets" >
                    <div class="form-group">
                        <label>Select Store</label>
                        <select class="form-control" name="storeId" onchange="document.formShifts.submit()">
                            <?php
                            foreach ($stores as $store) {
                                ?>
                                <option value="<?=$store->getId()?>" <?php if ($store->getId() == $_REQUEST["storeId"]) { ?> selected <?php } ?> ><?=$store->getName()?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>
                </div>

                <div class="col-md-2">
                    <label>Week Day</label>
                    <select class="form-control" name="weekDay">
                        <option value="1">Monday</option>
                        <option value="2">Tuesday</option>
                        <option value="3">Wednesday</option>
                        <option value="4">Thursday</option>
                        <option value="5">Friday</option>
                        <option value="6">Saturday</option>
                        <option value="7">Sunday</option>
                    </select>
                </div>
                <div class="col-md-2">
                    <label>Description</label>
                    <input class="form-control" type="text" name="description" placeholder="Description" required  data-validate='{"required":true}'>
                </div>
                <div class="col-md-2">
                    <label>Time From</label>
                    <input class="form-control" type="text" name="timeFrom" placeholder="00:00" data-validate='{"validate-time":true}'>
                </div>
                <div class="col-md-2">
                    <label>Time To</label>
                    <input class="form-control" type="text" name="timeTo" placeholder="00:00" data-validate='{"validate-time":true}'>
                </div>
                <div class="col-md-2">
                    <label>Price</label>
                    <input class="form-control" type="text" name="price" placeholder="0.00" >
                </div>
                <div class="col-md-1">
                    <label>Cuttoff Time</label>
                    <input class="form-control" type="text" name="cutoffTime" placeholder="12:00" >
                </div>
                <div class="col-md-1">
                    <br>
                    <input type="button" name="add" value="Add Shift" class="btn btn-primary" onclick="document.formShifts.submit()">
                </div>
            </div>
            <div class="row">

                <div class="col-md-12">
                    <hr>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Week Day</th>
                                <th>Description</th>
                                <th class="text-right">Time From</th>
                                <th class="text-right">Time To</th>
                                <th class="text-right">Price</th>
                                <th class="text-right">Cuttoff Time</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach ($shifts as $id => $shift) {
                        ?>
                            <tr>
                                <td><?=$WEEK_DAYS[$shift["delivery_day"]-1]?></td>
                                <td><?=$shift["description"]?></td>
                                <td class="text-right"><?=$shift["shift_start"]?></td>
                                <td class="text-right"><?=$shift["shift_end"]?></td>
                                <td class="text-right"><?=number_format($shift["price"], 2)?></td>
                                <td class="text-right"><?=$shift["cutoff_time"]?></td>
                                <td><a href="?data-target=buckets&storeId=<?=$_REQUEST["storeId"]?>&deleteId=<?=$shift["id"]?>" class="btn btn-danger">Delete</a></td>
                            </tr>

                        <?php
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </form>

</div>
<script type="text/javascript">

        require(['jquery'], function($) {
            $('.picupContent').hide();
            $(document).on("click", ".picupMenu", function(event) {
                $('.picupContent').hide();
                $('#'+$(event.target).attr('data-target')).show();
            });

            $('#<?=$_REQUEST["data-target"]?>').show();
        });

</script>
<!-- inline fixes until module is complete -->
<style>
    #buckets select, #buckets input {
        height: 3rem;
    }
</style>

<script type="text/javascript">
    require([
        'jquery',
        'jquery/ui',
        'jquery/validate',
        'mage/translate'
    ], function($){
        $.validator.addMethod(
            'validate-time', function (value) {
                return value.match(^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$);
            }, $.mage.__('Enter Valid Time')
        );
    });
</script>


