<?php
/**
 * Copyright 2020  Picup Technology (Pty) Ltd or its affiliates. All Rights Reserved.
 *
 * Licensed under the GNU General Public License, Version 3.0 or later(the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  https://opensource.org/licenses/GPL-3.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

$WEEK_DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

$request = $block->getRequest();

$stores = $block->getStores();



//Get the first store
if (empty($request->storeId)) {
    foreach ($stores as $store) {
        $request->storeId = $store->getId();
        break;
    }
}

//set the data target
if (empty($request->{"data-target"})) {
    $request->{"data-target"} = "warehouse";
}

if (!empty($request->deleteId)) {
    $block->deleteShift($request->deleteId);
}

if (!empty($request->weekDay) && !empty($request->description) && !empty($request->timeFrom)&& !empty($request->timeTo) && !empty($request->price)) {
    $block->addShift($request->storeId, $request->weekDay, $request->description, $request->timeFrom, $request->timeTo, $request->price, $request->cutoffTime);
}


$shifts = $block->getShifts($request->storeId);
?>
<link href="http://picup.co.za/assets/css/style.css" rel="stylesheet" />
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <button type="button" class="picupMenu btn btn-primary" data-target="warehouse">My Warehouse</button>
            <button type="button" class="picupMenu btn btn-primary" data-target="buckets">Buckets</button>
            <a href="<?=$block->getUrl("adminhtml/system_config/edit/section/carriers");?>" class="picupMenu btn btn-primary" data-target="shipping-settings">Store Settings</a>
        </div>
    </div>
    <hr/>
    <div id="warehouse" class="picupContent row">
        <div class="col-md-12">
            <iframe frameborder="0" style="width:100%; height: 90vh" src="https://staging.picup.co.za/login"></iframe>
        </div>
    </div>
    <form class="form" name="formShifts" data-mage-init='{
                "validation":{
                        "rules": {
                                "description": {
                                        "required":true
                                }
                        }
                }
        }'>
        <div id="buckets" class="picupContent">
            <div class="row">
                <div class="col-md-12">
                    <input type="hidden" name="data-target" value="buckets" >
                    <div class="form-group">
                        <label>Select Store</label>
                        <select class="form-control" name="storeId" onchange="document.formShifts.submit()">
                            <?php
                            foreach ($stores as $store) {
                                ?>
                                <option value="<?=$store->getId()?>" <?php if ($store->getId() == $request->storeId) { ?> selected <?php } ?> ><?=$store->getName()?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>
                </div>

                <div class="col-md-2">
                    <label>Week Day</label>
                    <select class="form-control" name="weekDay">
                        <option value="1">Monday</option>
                        <option value="2">Tuesday</option>
                        <option value="3">Wednesday</option>
                        <option value="4">Thursday</option>
                        <option value="5">Friday</option>
                        <option value="6">Saturday</option>
                        <option value="7">Sunday</option>
                    </select>
                </div>
                <div class="col-md-2">
                    <label>Description</label>
                    <input class="form-control" type="text" name="description" placeholder="Description" required  data-validate='{"required":true}'>
                </div>
                <div class="col-md-2">
                    <label>Time From</label>
                    <input class="form-control" type="text" name="timeFrom" placeholder="00:00" data-validate='{"validate-time":true}'>
                </div>
                <div class="col-md-2">
                    <label>Time To</label>
                    <input class="form-control" type="text" name="timeTo" placeholder="00:00" data-validate='{"validate-time":true}'>
                </div>
                <div class="col-md-2">
                    <label>Price</label>
                    <input class="form-control" type="text" name="price" placeholder="0.00" >
                </div>
                <div class="col-md-1">
                    <label>Cut-off Time</label>
                    <input class="form-control" type="text" name="cutoffTime" placeholder="12:00" >
                </div>
                <div class="col-md-1">
                    <br>
                    <input type="button" name="add" value="Add Shift" class="btn btn-primary" onclick="document.formShifts.submit()">
                </div>
            </div>
            <div class="row">

                <div class="col-md-12">
                    <hr>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Week Day</th>
                                <th>Description</th>
                                <th class="text-right">Time From</th>
                                <th class="text-right">Time To</th>
                                <th class="text-right">Price</th>
                                <th class="text-right">Cut-off Time</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach ($shifts as $id => $shift) {
                        ?>
                            <tr>
                                <td><?=$WEEK_DAYS[$shift["delivery_day"]-1]?></td>
                                <td><?=$shift["description"]?></td>
                                <td class="text-right"><?=$shift["shift_start"]?></td>
                                <td class="text-right"><?=$shift["shift_end"]?></td>
                                <td class="text-right"><?=number_format($shift["price"], 2)?></td>
                                <td class="text-right"><?=$shift["cutoff_time"]?></td>
                                <td><a href="?data-target=buckets&storeId=<?=$request->storeId?>&deleteId=<?=$shift["id"]?>" class="btn btn-danger">Delete</a></td>
                            </tr>

                        <?php
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </form>

</div>
<script type="text/javascript">

        require(['jquery'], function($) {
            $('.picupContent').hide();
            $(document).on("click", ".picupMenu", function(event) {
                $('.picupContent').hide();
                $('#'+$(event.target).attr('data-target')).show();
            });


            $('#<?=$request->{"data-target"}?>').show();
        });

</script>
<!-- inline fixes until module is complete -->
<style>
    #buckets select, #buckets input {
        height: 3rem;
    }
</style>

<script type="text/javascript">
    require([
        'jquery',
        'jquery/ui',
        'jquery/validate',
        'mage/translate'
    ], function($){
        $.validator.addMethod(
            'validate-time', function (value) {
                return value.match(^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$);
            }, $.mage.__('Enter Valid Time')
        );
    });
</script>


